version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - beverage-network
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/beverage_ecommerce
      - FRONTEND_URL=http://localhost:3001
      - BACKEND_URL=http://localhost:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: beverage_ecommerce
    networks:
      - beverage-network

  # Redis for session storage and caching (optional)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - beverage-network
    command: redis-server --appendonly yes

volumes:
  mongodb-data:
  redis-data:

networks:
  beverage-network:
    driver: bridge